# Generated by Django 4.2.23 on 2025-07-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='input_value',
            field=models.FloatField(default=0.0, help_text='Distance in km, kWh used, or meals eaten'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='co2_emitted',
            field=models.FloatField(editable=False, null=True),
        ),
    ]
