# Generated by Django 4.2.23 on 2025-07-21 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker1', '0005_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
