# Generated by Django 4.2.23 on 2025-07-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker1', '0006_remove_profile_user_delete_activity_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='monthly_co2_goal',
            field=models.FloatField(default=20.0),
        ),
    ]
